---
version: "2"
plugins:
    duplication:
        enabled: true
        config:
            languages:
            - ruby
            - javascript
            - python
            - php
    fixme:
        enabled: true
    phpmd:
        enabled: true
        checks:
            Design/EvalExpression:
                enabled: false
        exclude_fingerprints:
        # isBlockTag(MarkupElement $element) used by extended classes
        - 5ab33bda35b1024e2545fa3f9f81cd20
    phpcodesniffer:
        enabled: true
    SonarPHP:
        enabled: true
    phan:
        enabled: true
ratings:
    paths:
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
    - "**.rb"
exclude_patterns:
- "tests/"
