
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --prefer-stable --dev

install:
    - php bin/check $TRAVIS_PHP_VERSION install

script:
    - php bin/check $TRAVIS_PHP_VERSION

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z
