
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2

matrix:
    include:
        - php: hhvm-3.18
          dist: trusty
          sudo: required
        - php: hhvm-3.19
          dist: trusty
          sudo: required
        - php: hhvm-3.20
          dist: trusty
          sudo: required
        - php: hhvm-3.21
          dist: trusty
          sudo: required
        - php: hhvm-3.22
          dist: trusty
          sudo: required
        - php: hhvm-3.23
          dist: trusty
          sudo: required
        - php: hhvm-3.24
          dist: trusty
          sudo: required
    allow_failures:
        - php: hhvm-3.18
          dist: trusty
          sudo: required
        - php: hhvm-3.19
          dist: trusty
          sudo: required
        - php: hhvm-3.20
          dist: trusty
          sudo: required
        - php: hhvm-3.21
          dist: trusty
          sudo: required
        - php: hhvm-3.22
          dist: trusty
          sudo: required
        - php: hhvm-3.23
          dist: trusty
          sudo: required
        - php: hhvm-3.24
          dist: trusty
          sudo: required

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phug-dev check --report --coverage-php-version=5.6

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
    code_climate:
        repo_token: 9c0588d54489bc33e39a491695edf96ee097a0f071be4b89692836dedc70abad
